<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>fileTypes</key>
    <array>
        <string>crontab</string>
        <string>cron</string>
    </array>
    <key>name</key>
    <string>Crontab</string>
    <key>patterns</key>
    <array>
        <dict>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>keyword.at.crontab</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>string.command.crontab</string>
                </dict>
            </dict>
            <key>match</key>
            <string>^\s*(\@[^\s]+)\s+(.*)$\n?</string>
            <key>name</key>
            <string>meta.declaration.crontab</string>
        </dict>
        <dict>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>keyword.minute.crontab</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>constant.hour.crontab</string>
                </dict>
                <key>3</key>
                <dict>
                    <key>name</key>
                    <string>class.dayofmonth.crontab</string>
                </dict>
                <key>4</key>
                <dict>
                    <key>name</key>
                    <string>keyword.month.crontab</string>
                </dict>
                <key>5</key>
                <dict>
                    <key>name</key>
                    <string>constant.dayofweek.crontab</string>
                </dict>
                <key>6</key>
                <dict>
                    <key>name</key>
                    <string>string.command.crontab</string>
                </dict>
            </dict>
            <key>match</key>
            <string>^\s*([^\#\s\t]+)\s+([^\s\t]+)\s+([^\s\t]+)\s+([^\s\t]+)\s+([^\s\t]+)\s+(.*)$\n?</string>
            <key>name</key>
            <string>meta.declaration.crontab</string>
        </dict>
    </array>
    <key>scopeName</key>
    <string>crontab</string>
    <key>uuid</key>
    <string>3c4b8943-5779-4c8b-ba99-c65bbc144d44</string>
</dict>
</plist>
