[tool.ruff]
select = [
  "A",      # flake8-builtins
  "ASYNC",  # flake8-async
  "B",      # flake8-bugbear
  "BLE",    # flake8-blind-except
  "C4",     # flake8-comprehensions
  "C90",    # McCabe cyclomatic complexity
  "DTZ",    # flake8-datetimez
  "E",      # pycodestyle
  "EXE",    # flake8-executable
  "F",      # Pyflakes
  "FA",     # flake8-future-annotations
  "FBT",    # flake8-boolean-trap
  "FLY",    # flynt
  "ICN",    # flake8-import-conventions
  "INT",    # flake8-gettext
  "ISC",    # flake8-implicit-str-concat
  "N",      # pep8-naming
  "PGH",    # pygrep-hooks
  "PIE",    # flake8-pie
  "PL",     # Pylint
  "PT",     # flake8-pytest-style
  "PYI",    # flake8-pyi
  "RET",    # flake8-return
  "RSE",    # flake8-raise
  "RUF",    # Ruff-specific rules
  "S",      # flake8-bandit
  "SIM",    # flake8-simplify
  "SLF",    # flake8-self
  "T10",    # flake8-debugger
  "TCH",    # flake8-type-checking
  "TD",     # flake8-todos
  "TID",    # flake8-tidy-imports
  "W",      # pycodestyle
  "YTT",    # flake8-2020
  # "ANN",  # flake8-annotations
  # "ARG",  # flake8-unused-arguments
  # "COM",  # flake8-commas
  # "D",    # pydocstyle
  # "DJ",   # flake8-django
  # "EM",   # flake8-errmsg
  # "ERA",  # eradicate
  # "G",    # flake8-logging-format
  # "I",    # isort
  # "INP",  # flake8-no-pep420
  # "NPY",  # NumPy-specific rules
  # "PD",   # pandas-vet
  # "PTH",  # flake8-use-pathlib
  # "Q",    # flake8-quotes
  # "T20",  # flake8-print
  # "TRY",  # tryceratops
  # "UP",   # pyupgrade
]
ignore = ["N999", "PT009"]
line-length = 159
target-version = "py37"

[tool.ruff.mccabe]
max-complexity = 20

[tool.ruff.pylint]
allow-magic-value-types = ["int", "str"]
max-args = 8
max-branches = 16

[tool.ruff.per-file-ignores]
"cron_descriptor/Exception.py" = ["N818", "PIE790"]
"cron_descriptor/ExpressionDescriptor.py" = ["B904", "BLE001", "DTZ011", "PLC1901", "RET505"]
"cron_descriptor/ExpressionParser.py" = ["RET506"]
"setup.py" = ["SIM115"]
"tests/*" = ["PLR0402", "S101"]
"tests/TestLocale.py" = ["PIE804"]
"tools/resx2po.py" = ["N817", "S314"]
